window.langEN = {
    tab_home: "Home",
    tab_profile: "My Profile",
    page_title_home: "Children's Profiles",
    page_title_profile: "My Profile",
    
    no_profiles: "Profiles not added yet.",
    form_title_add: "Add Child",
    form_title_edit: "Edit Profile",
    label_lang: "Fairy Tales Language",
    label_name: "Name",
    placeholder_name: "Example: Timur",
    label_gender: "Gender",
    btn_boy: "Boy 👦",
    btn_girl: "Girl 👧",
    btn_save_add: "Add Profile",
    btn_save_edit: "Save Changes",
    btn_cancel: "Cancel",
    
    lbl_app_lang: "App Language",
    lbl_app_theme: "Theme",
    theme_day: "☀️ Day",
    theme_night: "🌙 Night",
    
    status_active: "✅ Active Subscription",
    status_trial: "⏳ Trial Period",
    status_inactive: "❌ Inactive",
    status_active_text: "Access open until {date}. Tales arrive every day!",
    status_trial_text: "Free access until {date}.",
    status_inactive_text: "Magic time is over. Renew your access.",
    btn_renew_active: "Renew for a month (24,500 sum)",
    btn_renew_trial: "Subscribe (24,500 sum)",
    btn_renew_inactive: "Renew subscription (24,500 sum)",
    
    lbl_new_stories: "✨ New Tales (Today)",
    empty_today: "A new fairy tale will appear today at 21:00!",
    lbl_archive_stories: "📚 My Tales (Archive)",
    empty_archive: "The archive is empty. Tales will appear here tomorrow.",
    paywall_text: "Access to the archive of past tales is available only in the paid plan.",
    paywall_btn: "Unlock Access (24,500 sum)",
    
    reader_header: "Fairy Tale",
    reader_back: "⬅ Back",
    
    modalTitle: "Tell us about yourself",
    modalSub: "This will help us make the fairy tales even better:",
    labelParentName: "Your name",
    parentNamePlaceholder: "e.g. Alexander",
    labelParentRole: "Who are you to the child?",
    roleMother: "Mother",
    roleFather: "Father",
    roleGrandma: "Grandmother",
    roleGrandpa: "Grandfather",
    roleNanny: "Nanny",
    roleOther: "Other",
    customRolePlaceholder: "Please specify...",
    labelParentAge: "Your age",
    parentAgePlaceholder: "e.g. 32",
    textPrivacy: 'I have read and agree to the <a href="#" onclick="openLink(configUrls.privacy_url)" style="color: #c084fc; text-decoration: underline;">Privacy Policy</a>',
    textOffer: 'I accept the terms of the <a href="#" onclick="openLink(configUrls.offer_url)" style="color: #c084fc; text-decoration: underline;">Offer Agreement</a>',
    saveParentBtn: "Continue",
    
    consent_text: "I accept the <a href='#' onclick='openLink(\"{offer}\")'>Terms of Service</a> and <a href='#' onclick='openLink(\"{privacy}\")'>Privacy Policy</a>",
    footer_privacy: "Privacy Policy",
    footer_offer: "Terms of Service",
    footer_about: "About the project"
};
